language: python
cache: pip
python:
  - "2.7"
  - "3.5.1"
# command to install dependencies
install:
  - pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt --only-binary=numpy,scipy
  - pip install jupyter
  - pip install atari_py
  - pip install hacking
  - pip install coveralls
  - git clone https://github.com/mgbellemare/Arcade-Learning-Environment.git
  - cd Arcade-Learning-Environment
  - cmake -DUSE_SDL=OFF -DUSE_RLGLUE=OFF -DBUILD_EXAMPLES=OFF
  - make
  - python setup.py install
  - cd ..
  - python setup.py develop
before_script:
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start
  - sleep 3
# command to run tests
script:
  - flake8 chainerrl
  - flake8 tests
  - flake8 examples
  - nosetests -a '!gpu,!slow' -x tests --with-coverage --cover-package chainerrl
  - ./test_examples.sh -1
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5.1 ]]; then jupyter nbconvert --to notebook --execute examples/quickstart/quickstart.ipynb --ExecutePreprocessor.timeout=600; fi
after_success:
  - coveralls
